### ISSUE TITLE
Add capability for additional args

### ISSUE THREAD

**Issue by ejether** [reactiveops/reckoner#2]
Carried over from: https://github.com/reactiveops/autohelm/issues/55

All in all, I think we could add a new multiple command line arg --helm-args, add a helm_args section to the course.yml spec and also per chart. As part of that, also deprecate the other command line args that are essentially just --helm-args but leaving the ones that require special logic. This would provide more than intended functionality, but also reduce the amount of changes required when new Helm args are released.

- [x]  add --helm-args to command line : https://github.com/reactiveops/autohelm/issues/54 
- [x] add helm_args section to course.yml
- [x] add deprecation warnings to  --debug flag
- [ ] remove --debug flag

Keep the existing reckoner --dry-run flag that will imply a helm dry-run and skip hooks.

**Comment by sudermanjr** [comment]
By delegating `--dry-run` to helm-args, we would currently drop the functionality of being able to disable hooks running on `dry-run`.  Not sure we should do that.

**Comment by ejether** [comment]
Hmm, not necessarily, because we could add a check for it in the `helm-arg` list but I'm not sure I like that better.

**Comment by sudermanjr** [comment]
I think a helm dry-run and a reckoner dry-run become two separate things.  we can go ahead and remove debug (especially since dry-run implies a helm debug), but I think dry-run should remain.

Adding helm-args to course.yml is still a great idea though

**Comment by ejether** [comment]
Would that make a reckoner dry run and helm dry run like:
`reckoner plot <course> --dry-run --helm-args=dry-run` our would reckoner `--dry-run` imply a helm `--dry-run`?

**Comment by sudermanjr** [comment]
My thinking is the second.  reckoner dry-run implies a `helm --dry-run --debug` and also skips all hooks
