### ISSUE TITLE
--recreate-pods set twice in tests for chart installation

### ISSUE THREAD

**Issue by ejether** [reactiveops/reckoner#37]
When fixing #34 and re-enabling the chart installation tests, I had to add `--recreate-pods` twice to the list of expected arguments in order for the tests to pass. 

https://github.com/reactiveops/reckoner/blob/a4452651e11d9de533ca2d503d26cd3f18dbe09f/tests/test_reckoner.py#L374
https://github.com/reactiveops/reckoner/blob/a4452651e11d9de533ca2d503d26cd3f18dbe09f/tests/test_reckoner.py#L393

**Comment by ejether** [comment]
I believe it is because and instance of the helm client is created and helm args are set:
https://github.com/reactiveops/reckoner/blob/master/reckoner/course.py#L58
then helm args are later appended again to the arguments per chart:
https://github.com/reactiveops/reckoner/blob/master/reckoner/chart.py#L212

**Comment by sudermanjr** [comment]
Fixed by #39 in  v0.10.2
